IlanSistemi/IlanSistemi.UI/Areas/Admin/Controllers/UrunController.cs
using IlanSistemi.Business.Concrete;
using IlanSistemi.DataAccess.Concrete;
using IlanSistemi.DataAccess.EntityFramework;
using IlanSistemi.Entities.Concrete;
using IlanSistemi.UI.Areas.User.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace IlanSistemi.UI.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Route("Admin/[controller]/[action]")]
	
	public class UrunController : Controller
	{
		private readonly DataContext _dataContext;

		public UrunController(DataContext dataContext)
		{
			_dataContext = dataContext;
		}

		private readonly AdvertManager _advertManager = new AdvertManager(new EfAdvertDal());
		private readonly CategoryAdvertManager _categoryAdvertManager = new CategoryAdvertManager(new EfCategoryAdvertDal());
		private readonly CategoryManager _categoryManager = new CategoryManager(new EfCategoryDal());
		private readonly UserManager _userManager = new UserManager(new EfUserDal());
		private readonly AdvertImageManager _advertImageManager = new AdvertImageManager(new EfAdvertImageDal());


		public IActionResult Index()
		{
			var values = _advertManager.TGetList();
			return View(values);
		}


		public IActionResult DeleteAdvert(int id)
		{

			var advertImages = _advertImageManager.TGetListbyFilter(ai => ai.AdvertId == id);
			foreach (var advertImage in advertImages)
			{
				_advertImageManager.TDelete(advertImage);
			}

			var categoryAdverts = _categoryAdvertManager.TGetListbyFilter(ca => ca.AdvertId == id);
			foreach (var categoryAdvert in categoryAdverts)
			{
				_categoryAdvertManager.TDelete(categoryAdvert);
			}


			var advert = _advertManager.TGetByID(id);
			_advertManager.TDelete(advert);

			return RedirectToAction("Index");
		}
	}
}

IlanSistemi/IlanSistemi.UI/Controllers/AdvertController.cs
using IlanSistemi.Business.Abstract;
using IlanSistemi.DataAccess.Concrete;
using IlanSistemi.Entities.Concrete;
using IlanSistemi.Entities.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IlanSistemi.UI.Controllers
{
	public class AdvertController : Controller
	{
		private readonly IAdvertService _advertService;
		private readonly IUserService _userService;
		private readonly ICategoryService _categoryService;
		private readonly ICategoryAdvertService _categoryAdvertService;
		private readonly IAdvertCommentService _advertCommentService;
		private readonly DataContext _dataContext;

		public AdvertController(IAdvertService advertService, IUserService userService, ICategoryService categoryService, DataContext dataContext, ICategoryAdvertService categoryAdvertService, IAdvertCommentService advertCommentService)
		{
			_advertService = advertService;
			_userService = userService;
			_categoryService = categoryService;
			_dataContext = dataContext;
			_categoryAdvertService = categoryAdvertService;
			_advertCommentService = advertCommentService;
		}

		[Route("advert/{advertId}")]
		public IActionResult Index(int advertId)
		{
			var advert = _advertService.GetAllAdvertsWithImage().Find(x => x.Advert.Id == advertId);

			if (advert == null)
			{
				return RedirectToAction("Error");
			}

			var user = _userService.TGetByID(advert.UserId);

			var advertComment = _dataContext.advertComments
				.FirstOrDefault(c => c.AdvertId == advertId);

			var advertComentList = _dataContext.advertComments.ToList();
			

			AdvertSingleVM advertSingleVM = new AdvertSingleVM
			{
				Advert = advert.Advert,
				AdvertImages = advert.AdvertImages,
				User = user,
				comment = advertComment,
				mert = advertComentList,
				SelectedAdvert = advert.Advert
			};

			return View(advertSingleVM);
		}



		[HttpPost]
		[Route("advert/{advertId}")]
		public IActionResult Comment(int advertId, string comment)
		{
			var advert = _advertService.GetAllAdvertsWithImage().FirstOrDefault(x => x.Advert.Id == advertId);

			if (advert is null)
				return RedirectToAction("Error");

			var user = _userService.TGetByID(advert.Advert.UsersId);

			if (user is null)
				return RedirectToAction("Error");

			AdvertComment newComment = new AdvertComment
			{
				AdvertId = advertId,
				UsersId = user.Id,
				Comment = comment,
				CreatedAt = DateTime.Now,
				IsActive = true
			};

			_advertCommentService.TAdd(newComment);

			return RedirectToAction("Index", new { advertId = advertId });
		}




	}
}

IlanSistemi/IlanSistemi.UI/Controllers/CategoryController.cs
using IlanSistemi.Business.Abstract;
using IlanSistemi.Business.Concrete;
using IlanSistemi.DataAccess.Concrete;
using IlanSistemi.Entities.Concrete;
using IlanSistemi.Entities.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using System.Net.NetworkInformation;

namespace IlanSistemi.UI.Controllers
{
	[AllowAnonymous]
	public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly DataContext _dataContext;

        public CategoryController(ICategoryService categoryService, DataContext dataContext)
        {
            _categoryService = categoryService;
            _dataContext = dataContext;
        }

        [Route("category/products")]
        public async Task<IActionResult> Index(string query)
        {
            ViewBag.Category = "Tüm kategorilerdeki ürünler";
            ViewBag.AdvertCount = _categoryService.TGetList().Count();
            var allAdverts = await _dataContext.categories
                .Include(c => c.CategoryAdverts)
                .ThenInclude(ca => ca.adverts)
                .ThenInclude(ca=> ca.advertImages)
                .ToListAsync();

            var adverts = allAdverts.SelectMany(a => a.CategoryAdverts)
                .Select(ca => ca.adverts).ToList();

            if (!String.IsNullOrEmpty(query))
            {
                adverts = adverts.Where(v => v.Title.ToLower().Contains(query.ToLower())).ToList();
                ViewBag.Category = $" '{query}' araması için ilanlar ";
            }
                
            return View(adverts);
        }

        

        [Route("category/elektronik-aletler")]
        public async Task<IActionResult> Elektronik()
        {

            var categoryAdverts = await _categoryService.GetCategoryAdverts(1);
            

            if (categoryAdverts?.Count == 0)
                ViewData["message"] = "Bu kategoride gösterilecek herhangi bir ürün yok.";

            ViewBag.Category = "Elektronik kategorisindeki ürünler";
            ViewBag.AdvertCount = categoryAdverts?.Count;
            return View(categoryAdverts);
        }

        [Route("category/moda-giyim")]
        public async Task<IActionResult> Moda()
        {
            var categoryAdverts = await _categoryService.GetCategoryAdverts(2);

            if (categoryAdverts?.Count == 0)
                ViewData["message"] = "Bu kategoride gösterilecek herhangi bir ürün yok.";

            ViewBag.Category = "Moda kategorisindeki ürünler";
            ViewBag.AdvertCount = categoryAdverts?.Count;

            return View(categoryAdverts);
        }

        [Route("category/ev-yasam")]
        public async Task<IActionResult> EvYasam()
        {

            //Getting Category with specific Id
            var categoryAdverts = await _categoryService.GetCategoryAdverts(3);

            if (categoryAdverts?.Count == 0)
                ViewData["message"] = "Bu kategoride gösterilecek herhangi bir ürün yok.";

            ViewBag.Category = "Ev Yaşam kategorisindeki ürünler";
            ViewBag.AdvertCount = categoryAdverts?.Count;

            return View(categoryAdverts);
        }

        [Route("category/spor-outdoor")]
        public async  Task<IActionResult> SporOutdoor()
        {

            //Getting Category with specific Id
            var categoryAdverts = await _categoryService.GetCategoryAdverts(4);

            if (categoryAdverts?.Count == 0)
                ViewData["message"] = "Bu kategoride gösterilecek herhangi bir ürün yok.";

            ViewBag.Category = "Spor, Outdoor kategorisindeki ürünler";
            ViewBag.AdvertCount = categoryAdverts?.Count;

            return View(categoryAdverts);
        }

        [Route("category/kisisel-bakim")]
        public async Task<IActionResult> Kozmetik()
        {

            //Getting Category with specific Id
            var categoryAdverts = await _categoryService.GetCategoryAdverts(5);

            if (categoryAdverts?.Count == 0)
                ViewData["message"] = "Bu kategoride gösterilecek herhangi bir ürün yok.";

            ViewBag.Category = "Kozmetik kategorisindeki ürünler";
            ViewBag.AdvertCount = categoryAdverts?.Count;

            return View(categoryAdverts);
        }



    }
}

IlanSistemi/IlanSistemi.UI/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IlanSistemi.UI.Controllers
{
	[AllowAnonymous]
	public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public PartialViewResult FooterBottomPartial()
        {
            return PartialView();
        }

        public PartialViewResult FooterSectionPartial() 
        {
            return PartialView();
        }

        public PartialViewResult ScriptPartial()
        {
            return PartialView();
        }
        public PartialViewResult NavbarPartial() 
        {
            return PartialView();
        }

        public PartialViewResult HeadPartial() 
        {
            return PartialView();
        }
        public PartialViewResult HeadContentPartial()
        {
            return PartialView();
        }
    }
}

IlanSistemi/IlanSistemi.UI/Controllers/StaticController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IlanSistemi.UI.Controllers
{
	[AllowAnonymous]
	public class StaticController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
    }
}

IlanSistemi/IlanSistemi.UI/Views/Default/CategoryPartial.cshtml
@using IlanSistemi.Entities.Concrete;
@model List<Advert>;
<div class="row mt-30">
    @if (ViewData["message"] is null)
    {
        @foreach (var item in Model)
        {
            var title = item.Title.Length > 18 ? item.Title.Substring(0, 18) + "..." : item.Title;
            <div class="col-sm-12 col-lg-4 col-md-6">
                <div class="product-item bg-light">
                    <div class="card">
                        <div class="thumb-content">
                            <!-- <div class="price">$200</div> -->
                            <a asp-controller="Advert" asp-action="Index" asp-route-advertId="@item.Id">
                                <img class="card-img-top img-fluid" style="object-fit: cover; height: 200px;" src="~/UrunResimleri/@item.advertImages?.FirstOrDefault(x => x.AdvertId == item.Id).ImagePath" alt="Card image cap">
                            </a>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title"><a asp-controller="Advert" asp-action="Index" asp-route-advertId="@item.Id">@title</a></h4>
                            <ul class="list-inline product-meta">
                                <li class="list-inline-item">
                                    <a asp-controller="Advert" asp-action="Index" asp-route-advertId="@item.Id"><i class="fa fa-folder-open-o"></i>@item.Description</a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#"><i class="fa fa-calendar"></i>@item.CreatedAt</a>
                                </li>
                            </ul>
                            <p class="card-text">@item.Description</p>
                            <div class="product-ratings">
                                <ul class="list-inline">
                                    <li class="list-inline-item selected"><i class="fa fa-star"></i></li>
                                    <li class="list-inline-item selected"><i class="fa fa-star"></i></li>
                                    <li class="list-inline-item selected"><i class="fa fa-star"></i></li>
                                    <li class="list-inline-item selected"><i class="fa fa-star"></i></li>
                                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        }

    }
    else
    {
        <h2>@ViewData["message"]</h2>
    }

</div>

IlanSistemi/IlanSistemi.UI/Views/Default/FooterBottomPartial.cshtml
<footer class="footer-bottom">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-sm-6 col-12">
				<!-- Copyright -->
				<div class="copyright">
					<p>
						Copyright © <script>
							var CurrentYear = new Date().getFullYear()
							document.write(CurrentYear)
						</script>. All Rights Reserved, theme by <a class="text-primary" href="https://themefisher.com" target="_blank">themefisher.com</a>
					</p>
				</div>
			</div>
			<div class="col-sm-6 col-12">
				<!-- Social Icons -->
				<ul class="social-media-icons text-right">
					<li><a class="fa fa-facebook" href="https://www.facebook.com/themefisher" target="_blank"></a></li>
					<li><a class="fa fa-twitter" href="https://www.twitter.com/themefisher" target="_blank"></a></li>
					<li><a class="fa fa-pinterest-p" href="https://www.pinterest.com/themefisher" target="_blank"></a></li>
					<li><a class="fa fa-vimeo" href=""></a></li>
				</ul>
			</div>
		</div>
	</div>
	<!-- Container End -->
	<!-- To Top -->
	<div class="top-to">
		<a id="top" class="" href="#"><i class="fa fa-angle-up"></i></a>
	</div>
</footer>

IlanSistemi/IlanSistemi.UI/Views/Default/FooterSectionPartial.cshtml
<footer class="footer section section-sm">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-7 offset-md-1 offset-lg-0">
				<!-- About -->
				<div class="block about">
					<!-- footer logo -->
					<img src="~/template/images/logo-footer.png" alt="">
					<!-- description -->
					<p class="alt-color">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
						incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
						laboris nisi ut aliquip ex ea commodo consequat.
					</p>
				</div>
			</div>
			<!-- Link list -->
			<div class="col-lg-2 offset-lg-1 col-md-3">
				<div class="block">
					<h4>Site Pages</h4>
					<ul>
						<li><a href="#">Boston</a></li>
						<li><a href="#">How It works</a></li>
						<li><a href="#">Deals & Coupons</a></li>
						<li><a href="#">Articls & Tips</a></li>
						<li><a href="terms-condition.html">Terms & Conditions</a></li>
					</ul>
				</div>
			</div>
			<!-- Link list -->
			<div class="col-lg-2 col-md-3 offset-md-1 offset-lg-0">
				<div class="block">
					<h4>Admin Pages</h4>
					<ul>
						<li><a href="Category.html">Category</a></li>
						<li><a href="single.html">Single Page</a></li>
						<li><a href="store.html">Store Single</a></li>
						<li>
							<a href="single-blog.html">Single Post</a>
						</li>
						<li><a href="blog.html">Blog</a></li>



					</ul>
				</div>
			</div>
			<!-- Promotion -->
			<div class="col-lg-4 col-md-7">
				<!-- App promotion -->
				<div class="block-2 app-promotion">
					<div class="mobile d-flex">
						<a href="">
							<!-- Icon -->
							<img src="~/template/images/footer/phone-icon.png" alt="mobile-icon">
						</a>
						<p>Get the Dealsy Mobile App and Save more</p>
					</div>
					<div class="download-btn d-flex my-3">
						<a href="#"><img src="~/template/images/apps/google-play-store.png" class="img-fluid" alt=""></a>
						<a href="#" class=" ml-3"><img src="~/template/images/apps/apple-app-store.png" class="img-fluid" alt=""></a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Container End -->
</footer>

IlanSistemi/IlanSistemi.UI/Views/Default/HeadContentPartial.cshtml
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<!-- Header Contetnt -->
			<div class="content-block">
				<h1>Alıp & Satmak Çok Yakınınızda </h1>
				<p>Dünyadaki diğer topluluklarla birlikte  <br> Birbirlerinden alıp satan milyonlara katılın </p>
				<div class="short-popular-Category-list text-center">
					<h2>Popüler Kategoriler</h2>
					<ul class="list-inline">
						<li class="list-inline-item">
							<a asp-controller="category" asp-action="Elektronik"><i class="fa fa-bolt"></i> Elektronik</a>
						</li>
						<li class="list-inline-item">
							<a asp-controller="category" asp-action="Moda"><i class="fa fa-female"></i> Moda</a>
						</li>
						<li class="list-inline-item">
							<a asp-controller="category" asp-action="EvYasam"><i class="fa fa-home"></i> Ev, Yaşam</a>
						</li>
						<li class="list-inline-item">
							<a asp-controller="category" asp-action="SporOutdoor"><i class="fa fa-heart-o"></i> Spor, Outdoor</a>
						</li>
						<li class="list-inline-item">
							<a asp-controller="category" asp-action="Kozmetik"><i class="fa fa-sun-o"></i> Kozmetik</a>
						</li>
					</ul>
				</div>

			</div>
			<!-- Advance Search -->
			<div class="advance-search">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-lg-12 col-md-12 align-content-center">
							<form asp-controller="Category" asp-action="Index" method="get">
								<div class="form-row justify-content-center">
									<div class="form-group col-md-6">
										<input type="text" class="form-control my-2 my-lg-1" id="inputtext4" name="query" placeholder="Neye bakmıştın canım....">
									</div>								
									<div class="form-group col-md-2 align-self-center">
										<button type="submit" class="btn btn-primary">Şimdi Ara</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

IlanSistemi/IlanSistemi.UI/Views/Default/HeadPartial.cshtml
<head>
	<!-- SITE TITTLE -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>@ViewData["Title"]</title>

	<!-- FAVICON -->
	<link href="~/template/img/favicon.png" rel="shortcut icon">
	<!-- PLUGINS CSS STYLE -->
	<!-- <link href="plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet"> -->
	<!-- Bootstrap -->
	<link rel="stylesheet" href="~/template/plugins/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/template/plugins/bootstrap/css/bootstrap-slider.css">
	<!-- Font Awesome -->
	<link href="~/template/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<!-- Owl Carousel -->
	<link href="~/template/plugins/slick-carousel/slick/slick.css" rel="stylesheet">
	<link href="~/template/plugins/slick-carousel/slick/slick-theme.css" rel="stylesheet">
	<!-- Fancy Box -->
	<link href="~/template/plugins/fancybox/jquery.fancybox.pack.css" rel="stylesheet">
	<link href="~/template/plugins/jquery-nice-select/css/nice-select.css" rel="stylesheet">
	<!-- CUSTOM CSS -->
	<link href="~/template/css/style.css" rel="stylesheet">


	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

IlanSistemi/IlanSistemi.UI/Views/Default/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}


<!--===============================
=            Hero Area            =
================================-->

<section class="hero-area bg-1 text-center overly">
	<!-- Container Start -->
	@await Html.PartialAsync("/Views/Default/HeadContentPartial.cshtml")
	<!-- Container End -->
</section>

<!--===================================
=            Client Slider            =
====================================-->
<!--===========================================
=            Popular deals section            =
============================================-->
@await Component.InvokeAsync("TrendingAdds")


<!--==========================================
=            All Category Section            =
===========================================-->

<section class=" section">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			@await Component.InvokeAsync("CategoryAdds")

			
		</div>
	</div>
	<!-- Container End -->
</section>
<!--====================================
=            Call to Action            =
=====================================-->

<section class="call-to-action overly bg-3 section-sm">
	<!-- Container Start -->
	<div class="container">
		<div class="row justify-content-md-center text-center">
			<div class="col-md-8">
				<div class="content-holder">
					<h2>
						Start today to get more exposure and
						grow your business
					</h2>
					<ul class="list-inline mt-30">
						<li class="list-inline-item"><a class="btn btn-main" asp-area="User" asp-controller="Urun" asp-action="AddAdvert">İlan Ekle</a></li>
						<li class="list-inline-item"><a class="btn btn-secondary" asp-controller="Category" asp-action="Index">İlanları Gör</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>

IlanSistemi/IlanSistemi.UI/Views/Default/NavbarPartial.cshtml
<section>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<nav class="navbar navbar-expand-lg navbar-light navigation">
					<a class="navbar-brand" href="/">
						<img src="~/template/images/logo.png" alt="">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
							aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav ml-auto main-nav ">
							<li class="nav-item active">
								<a class="nav-link" href="/">Anasayfa</a>
							</li>
							<li class="nav-item dropdown dropdown-slide">
								<a class="nav-link dropdown-toggle" data-toggle="dropdown" asp-controller="Category" asp-action="Index">
									Kategoriler<span><i class="fa fa-angle-down"></i></span>
								</a>

								<!-- Dropdown list -->
								<div class="dropdown-menu">
									<a class="dropdown-item" asp-controller="Category" asp-action="Elektronik">Elektronik</a>
									<a class="dropdown-item" asp-controller="Category" asp-action="Moda">Moda</a>
									<a class="dropdown-item" asp-controller="Category" asp-action="EvYasam">Ev, Yaşam</a>
									<a class="dropdown-item" asp-controller="Category" asp-action="SporOutdoor">Spor, Outdoor</a>
									<a class="dropdown-item" asp-controller="Category" asp-action="Kozmetik">Kozmetik</a>
									<a class="dropdown-item" asp-controller="Category" asp-action="Index">Tüm kategorilerdeki ürünler</a>		
									
								</div>
							</li>
							<li class="nav-item dropdown dropdown-slide">
								<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Sayfalar <span><i class="fa fa-angle-down"></i></span>
								</a>
								<!-- Dropdown list -->
								<div class="dropdown-menu">
									<a class="dropdown-item"  asp-controller="Static" asp-action="About" >Hakkımızda</a>
									<a class="dropdown-item"  asp-controller="Static" asp-action="Contact"  >Bize Ulaşın</a>
									<a class="dropdown-item"  asp-area="User" asp-controller="Dashboard" asp-action="Index">Kullanıcı Profili</a>
								</div>
							</li>
						</ul>
						@await Component.InvokeAsync("LoginList")
						
					</div>
				</nav>
			</div>
		</div>
	</div>
</section>

IlanSistemi/IlanSistemi.UI/Views/Default/ScriptPartial.cshtml
<script src="~/template/plugins/jQuery/jquery.min.js"></script>
<script src="~/template/plugins/bootstrap/js/popper.min.js"></script>
<script src="~/template/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="~/template/plugins/bootstrap/js/bootstrap-slider.js"></script>
<!-- tether js -->
<script src="~/template/plugins/tether/js/tether.min.js"></script>
<script src="~/template/plugins/raty/jquery.raty-fa.js"></script>
<script src="~/template/plugins/slick-carousel/slick/slick.min.js"></script>
<script src="~/template/plugins/jquery-nice-select/js/jquery.nice-select.min.js"></script>
<script src="~/template/plugins/fancybox/jquery.fancybox.pack.js"></script>
<script src="~/template/plugins/smoothscroll/SmoothScroll.min.js"></script>
<!-- google map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"></script>
<script src="~/template/plugins/google-map/gmap.js"></script>
<script src="~/template/js/script.js"></script>

IlanSistemi/IlanSistemi.UI/Views/Default/_FooterBottomPartial.cshtml
<footer class="footer-bottom">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-sm-6 col-12">
				<!-- Copyright -->
				<div class="copyright">
					<p>
						Copyright © <script>
							var CurrentYear = new Date().getFullYear()
							document.write(CurrentYear)
						</script>. All Rights Reserved, theme by <a class="text-primary" href="https://themefisher.com" target="_blank">themefisher.com</a>
					</p>
				</div>
			</div>
			<div class="col-sm-6 col-12">
				<!-- Social Icons -->
				<ul class="social-media-icons text-right">
					<li><a class="fa fa-facebook" href="https://www.facebook.com/themefisher" target="_blank"></a></li>
					<li><a class="fa fa-twitter" href="https://www.twitter.com/themefisher" target="_blank"></a></li>
					<li><a class="fa fa-pinterest-p" href="https://www.pinterest.com/themefisher" target="_blank"></a></li>
					<li><a class="fa fa-vimeo" href=""></a></li>
				</ul>
			</div>
		</div>
	</div>
	<!-- Container End -->
	<!-- To Top -->
	<div class="top-to">
		<a id="top" class="" href="#"><i class="fa fa-angle-up"></i></a>
	</div>
</footer>